Repository sds/overcommit, pull requests merged in 2019-10, with the labels that each got.

#679 Fix markdown lint errors output #678
  lib/overcommit/hook/pre_commit/mdl.rb
  spec/overcommit/hook/pre_commit/mdl_spec.rb
Labels: bug

#682 Add Test on Hook Base "run?" Method
  spec/overcommit/hook/base_spec.rb
Labels: enhancement

#684 Add support for golangci-lint #680
  config/default.yml
  lib/overcommit/hook/pre_commit/golangci_lint.rb
  lib/overcommit/hook/pre_push/golangci_lint.rb
  spec/overcommit/hook/pre_commit/golangci_lint_spec.rb
  spec/overcommit/hook/pre_push/golangci_lint_spec.rb
Labels: enhancement

#689 Update Doc on "exclude_branch_patterns" config
  README.md
Labels: documentation

#683 Introduce "exclude_remote_names" to Skip Hook During PrePush Based on Remote Name
  lib/overcommit/hook/base.rb
  lib/overcommit/hook/pre_push/base.rb
  spec/overcommit/hook/pre_push/base_spec.rb
Labels: enhancement

#690 Introduce 'ignore_branch_deletions' Config for PrePush Hooks
  lib/overcommit/hook/pre_push/base.rb
  lib/overcommit/hook_context/pre_push.rb
  spec/overcommit/hook/pre_push/base_spec.rb
  spec/overcommit/hook_context/pre_push_spec.rb
Labels: enhancement

#692 [PrePush::ProtectedBranches] Implement setting destructive_only per branch
  lib/overcommit/hook/pre_push/protected_branches.rb
  spec/integration/protected_branches_spec.rb
  spec/overcommit/hook/pre_push/protected_branches_spec.rb
Labels: enhancement
